#! /bin/sh
set -v
rbox d D3 | qhull s Gnrv Tc Tv >eg.t01.spheres.3
rbox d D2 | qhull s Gnv  Tc Tv >eg.t02.spheres.2
rbox d D3 | qhull s Gnrp Tc Tv >eg.t03.points.3
rbox d D2 | qhull s Gnp Tc Tv >eg.t04.points.2
rbox c D4 | qhull s C0.05 GnpcD3 Pd3:0.5 Tc Tv >eg.t05.centrum.points.4-3
rbox d D3 | qhull s Gnrc Tc Tv >eg.t06.centrums.3.precise
rbox d D3 | qhull s C0.05 Gnrc Tc Tv >eg.t07.centrums.3
rbox d D2 | qhull s C0.05 Gc Tc Tv >eg.t08.centrums.2
rbox d D3 | qhull s Gnha Tc Tv >eg.t09.intersect.3
rbox d D3 | qhull s GaD0 Pd0 Tc Tv >eg.t10.faces.3-2
rbox d D3 | qhull s GnrpD0 Pd0 Tc Tv >eg.t11.points.3-2
rbox d D3 | qhull s C0.05 GnrcD0 Pd0 Tc Tv >eg.t12.centrums.3-2
rbox d D3 | qhull s GnhaD0 Pd0 Tc Tv >eg.t13.intersect.3-2
rbox d D3 | qhull s GnrvD0 Pd0 Tc Tv >eg.t14.spheres.3-2
rbox c D4 | qhull s GvD0 Pd0:0.5 Tc Tv >eg.t15.spheres.4-3
rbox c D4 | qhull s Q0 C0 GpD0 Pd0:0.5 Tc Tv >eg.t16.points.4-3
rbox c D4 | qhull s GahD0 Pd0:0.5 Tc Tv >eg.t17.intersect.4-3
rbox 100 s | qhull s C-0.05 Qc Gicvprh Tc Tv >eg.t18.imprecise.3
rbox 30 s D4 | qhull s GhD0 Pd0d1d2D3 Tc >eg.t19.intersect.precise.4-3
rbox 100 s P1,1,1 | qhull s QG-0 Pgp Tc G >eg.t20.notvisible
rbox 100 s | qhull s QV-10 Pgp Tc G  >eg.t21.notvertex
rbox 100 r D2 P1,1 | qhull s Pd0:0.7 PD0:0.8 QgG0 G Tv >eg.t22.split
rbox 100 D2 c G1.0 | qhull s A-0.95 v Gna Tv >eg.t23.voronoi.imprecise
rbox 30 s D4 | qhull s Gh Pd0d1d2D3 Tc >eg.t24.intersect.precise.4d

echo ==the following generates an error== >/dev/null
rbox 1000 D4 | qhull Q0 s Po R0.005 Ga Tc Tv >eg.t25.neighbors.4d
echo ==the previous should generate an error== >/dev/null


