#ifndef DB_PLANNER_RETRIEVE_FEATURES_FROM_DB_FUNCTOR_H
#define DB_PLANNER_RETRIEVE_FEATURES_FROM_DB_FUNCTOR_H

namespace db_planner {

  RetrieveFeaturesFromDbFunctor {
  }

}

#endif  // DB_PLANNER_RETRIEVE_FEATURES_FROM_DB_FUNCTOR_H
